[2013-11-11 06:36:32,929 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-11 06:36:32,930 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:36:32,932 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:36:34,019 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-11 06:36:34,020 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:36:34,022 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:36:34,358 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-11 06:36:34,359 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:36:34,361 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:36:34,534 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-11 06:36:34,535 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:36:34,537 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:36:34,764 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-11 06:36:34,766 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:36:34,768 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:36:34,891 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-11 06:36:34,893 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:36:34,895 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:37:56,356 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-11 06:37:56,358 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:37:56,361 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:37:57,164 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-11 06:37:57,165 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:37:57,168 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:37:57,456 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-11 06:37:57,458 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:37:57,461 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:37:57,865 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-11 06:37:57,867 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:37:57,869 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:37:58,046 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-11 06:37:58,048 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:37:58,050 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:37:58,200 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-11 06:37:58,202 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:37:58,206 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:37:58,406 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-11 06:37:58,409 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:37:58,412 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:37:58,558 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-11 06:37:58,561 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:37:58,563 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:38:18,795 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-11 06:38:18,799 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:38:18,802 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:38:27,471 UTC] [tuf.interposition] [INFO][info:33@utility.py] Updater added for Configuration(netloc=toannv.com:80).
[2013-11-11 06:38:41,249 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:38:41,252 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:38:46,063 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:38:46,066 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:38:46,689 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:38:46,693 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:38:46,892 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:38:46,896 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:38:47,062 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:38:47,066 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:38:47,239 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:38:47,244 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:38:47,409 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:38:47,414 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:38:47,557 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:38:47,561 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:38:47,732 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:38:47,737 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:38:47,910 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:38:47,915 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:39:58,921 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:39:58,927 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:40:02,518 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:40:02,523 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:40:40,439 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:40:40,444 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:40:51,257 UTC] [tuf.interposition] [INFO][info:33@utility.py] Updater added for Configuration(netloc=toannv.com:80).
[2013-11-11 06:41:04,685 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:41:04,685 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:41:32,706 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-11 06:41:32,707 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com/tuf!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:41:32,707 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:41:43,507 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:41:43,507 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:41:55,970 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid repository mirror www.toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 210, in __check_configuration_on_add
    assert mirror_hostname not in self.__repository_mirror_hostnames
AssertionError
[2013-11-11 06:41:55,971 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com/tuf!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:41:55,971 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 216, in __check_configuration_on_add
    raise InvalidConfiguration(error_message)
InvalidConfiguration: Invalid repository mirror www.toannv.com!
[2013-11-11 06:42:50,874 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration for toannv.com!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
[2013-11-11 06:42:50,876 UTC] [tuf.interposition] [ERROR][exception:28@utility.py] Invalid configuration in tuf.interposition.json!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/__init__.py", line 199, in __read_configuration
    configuration_handler(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 227, in add
    repository_mirror_hostnames = self.__check_configuration_on_add(configuration)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tuf/interposition/updater.py", line 198, in __check_configuration_on_add
    assert configuration.hostname not in self.__updaters
AssertionError
